# Header
menu:
  Home: /
  The Awakening: /The-Awakening
  Strategy: /Strategy
  AppVilla: /AppVilla
  TechnoSpace: /TechnoSpace
  Dear Diary: /Dear-Diary
  ScribblePad: /ScribblePad
  Whats in a name: /Whats-in-a-name
  
  
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-56262265-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: