# Header
menu:
  Home: /
  The Awakening: /The-Awakening
  The Name: /The-Name
  The Strategy: /Strategy
  AppVilla: /AppVilla
  TechnoSpace: /TechnoSpace
  Dear Diary: /tags/Dear-Diary
  ScribblePad: https://trello.com/b/mixkzFP8/scribblepad
  Whats in a name: /Whats-in-a-name
  
  
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tag
- tagcloud
- archive


# Miscellaneous
google_analytics: UA-56262265-1
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id: